apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: riviera-dev-realm
spec:
  keycloakCRName: keycloak-kubernetes-quickstart
  realm:
    id: riviera-dev-realm
    realm: riviera-dev-realm
    displayName: 'Riviera Dev workshop'
    enabled: true
    roles:
      realm:
      - name: user
        description: 'User realm role'
        composite: false
        clientRole: false
        containerId: riviera-dev-realm
        attributes: {}
      - name: admin
        description: 'Admin realm role'
        composite: false
        clientRole: false
        containerId: riviera-dev-realm
        attributes: {}
    clients:
    - clientId: quarkus-backend
      name: ''
      description: ''
      rootUrl: http://api.${NAMESPACE}.${MINIKUBE_IP}.nip.io
      adminUrl: http://api.${NAMESPACE}.${MINIKUBE_IP}.nip.io
      baseUrl: ''
      surrogateAuthRequired: false
      enabled: true
      alwaysDisplayInConsole: false
      clientAuthenticatorType: client-secret
      secret: "1LZ65XcapsfnwEOLsByUW7KKv05mGsZF"
      redirectUris:
      - http://api.${NAMESPACE}.${MINIKUBE_IP}.nip.io/*
      webOrigins:
      - http://api.${NAMESPACE}.${MINIKUBE_IP}.nip.io
      notBefore: 0
      bearerOnly: false
      consentRequired: false
      standardFlowEnabled: false
      implicitFlowEnabled: false
      directAccessGrantsEnabled: true
      serviceAccountsEnabled: false
      publicClient: false
      frontchannelLogout: true
      protocol: openid-connect
      attributes:
        oidc.ciba.grant.enabled: 'false'
        client.secret.creation.time: '1719400238'
        backchannel.logout.session.required: 'true'
        oauth2.device.authorization.grant.enabled: 'false'
        backchannel.logout.revoke.offline.tokens: 'false'
      authenticationFlowBindingOverrides: {}
      fullScopeAllowed: true
      nodeReRegistrationTimeout: -1
      defaultClientScopes:
      - web-origins
      - acr
      - roles
      - profile
      - basic
      - email
      optionalClientScopes:
      - address
      - phone
      - offline_access
      - microprofile-jwt
    users:
    - username: admin
      firstName: Administrator
      lastName: The Main
      email: admin@email.com
      emailVerified: false
      createdTimestamp: 1719423923528
      enabled: true
      totp: false
      credentials:
        - id: ad90997f-e6a8-495f-a5ad-361aa7bca1ed
          type: password
          userLabel: My password
          createdDate: 1719423932260
          secretData: '{"value":"KhrltyeRCFpTR6y5zV2SotExbMLQ7jOBg4EajpOFkWU=","salt":"qdoQ5ldVyocf+4z0m7XsjQ==","additionalParameters":{}}'
          credentialData: '{"hashIterations":5,"algorithm":"argon2","additionalParameters":{"hashLength":["32"],"memory":["7168"],"type":["id"],"version":["1.3"],"parallelism":["1"]}}'
      disableableCredentialTypes: []
      requiredActions: []
      realmRoles:
        - admin
        - user
        - default-roles-riviera-dev-realm
      notBefore: 0
      groups: []
    - username: user
      firstName: User
      lastName: The First
      email: user@email.com
      emailVerified: false
      createdTimestamp: 1719424016489
      enabled: true
      totp: false
      credentials:
        - id: 5be1cf70-6c35-45b5-8a32-e0f440512178
          type: password
          userLabel: My password
          createdDate: 1719424028381
          secretData: '{"value":"7n+7kp4MByv1whJHb7N3KJSiJW+0IV1xEsYukhrtL6g=","salt":"hcYtWpmf4TL09UizIYAMWg==","additionalParameters":{}}'
          credentialData: '{"hashIterations":5,"algorithm":"argon2","additionalParameters":{"hashLength":["32"],"memory":["7168"],"type":["id"],"version":["1.3"],"parallelism":["1"]}}'
      disableableCredentialTypes: []
      requiredActions: []
      realmRoles:
        - user
        - default-roles-riviera-dev-realm
      notBefore: 0
      groups: []