spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.keycloak-namespace.192.168.49.2.nip.io/realms/riviera-dev-realm/protocol/openid-connect/certs
